const security=[{bearerAuth:[]}];
const refreshBody={required:true,content:{'application/json':{schema:{type:'object',required:['refreshToken'],properties:{refreshToken:{type:'string'}}}}}};
export const mobilePaths={
 '/auth/refresh':{post:{tags:['Auth'],summary:'Renouveler la session et faire tourner le refresh token',security:[],requestBody:refreshBody,responses:{'200':{description:'token, refreshToken et user'},'401':{description:'Refresh token expiré ou déjà utilisé'}}}},
 '/auth/logout':{post:{tags:['Auth'],summary:'Révoquer le refresh token',security:[],requestBody:refreshBody,responses:{'204':{description:'Session révoquée'}}}},
 '/mobile/bootstrap':{get:{tags:['Mobile'],summary:'Référentiel du secteur assigné : events, items, tasks, deliveries, anomalies, notifications, people',security,responses:{'200':{description:'Cache complet filtré selon les affectations et le rôle'},'401':{description:'Authentification requise'}}}},
 '/mobile/operations':{post:{tags:['Mobile'],summary:'Appliquer une action locale avec déduplication et verrouillage optimiste',security,requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['id','kind','entityId','expected','action','data'],properties:{id:{type:'string',description:'Identifiant stable conservé lors des reprises'},kind:{type:'string',enum:['item','task','delivery','anomaly']},entityId:{type:'string',description:'Pour une anomalie, identifiant de l’équipement'},expected:{type:'string',format:'date-time',description:'updatedAt de la version connue'},action:{type:'string',enum:['scanned','moved','transferred','maintenance','status','validate','report']},data:{type:'object',additionalProperties:true}}}}}},responses:{'200':{description:'status: applied et entity ; une reprise ne rejoue pas l’action'},'403':{description:'Rôle ou affectation insuffisante'},'409':{description:'Conflit : details.current contient la version serveur'},'422':{description:'Validation refusée'}}}},
 '/mobile/stream':{get:{tags:['Mobile'],summary:'SSE authentifié : invalidation du cache après une mutation, avec heartbeat',security,responses:{'200':{description:'Événements data: {type: refresh}',content:{'text/event-stream':{schema:{type:'string'}}}}}}}
};
