---
all:
  children:
    production:
      hosts:
        logichain:
          ansible_host: "{{ lookup('env', 'DEPLOY_HOST') }}"
          ansible_user: "{{ lookup('env', 'DEPLOY_USER') | default('deploy', true) }}"
          ansible_port: 22
